[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
sonolil_core = { path = "../../lib/_core" }
sonolil_basic2d = { path = "../../lib/basic2d" }
sonolil_editor = { path = "../../lib/editor" }

bevy.workspace = true

egui.workspace = true
egui_dock.workspace = true
bevy_egui.workspace = true