[workspace]
members = [
	"all",
	"lib/*",
	"test/*"
]

resolver = "2"
default-members = ["all", "test/editor"] # Always include 'all'

# Enable fast linking and dynamic linking optimization for development
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[workspace.dependencies]
# Core Framework
bevy = "0.19.1"
bevy_dev_tools = { "version" = "0.19.1", features = ["schedule_data", "screenrecording"] }
bevy_framepace = "0.22"
moonshine-core = "0.6.0"

# GUI
egui = { version = "0.34" }
egui_dock = { "version" = "0.19.1", features = ["serde"] }
egui_ltreeview = { "version" = "0.7.1", features = ["persistence"] }
egui-keyframe = { git = "https://github.com/virtualritz/egui-keyframe.git", rev = "2eb3da4d3f72f7fc47a085b78cab345b5382a85a" }
bevy_egui = { version = "0.40.0" }
bevy-inspector-egui = "0.37.0"
bevy_gltf = { "version" = "0.19.1", features = ["bevy_animation", "pbr_anisotropy_texture", "pbr_multi_layer_material_textures", "pbr_specular_textures", "pbr_transmission_textures"] }

# Input Handling / Action Mapping
leafwing-input-manager = { version = "0.21", features = ["timing"] }

# Asset Related
bevy_kira_audio = { version = "0.26", features = ["ogg", "flac", "mp3", "wav"] }
bevy_asset_loader = { version = "0.27.0", features = ["2d", "3d", "progress_tracking", "standard_dynamic_assets"] }
iyes_progress = { version = "0.17.0", features = ["assets", "async", "debug"] }

# Tilemap & Level Design
bevy_ecs_tilemap = "0.19.0"
bevy_ecs_tiled = "0.13" 
bevy_ecs_ldtk = "0.15.0" 
bevy_northstar = "0.7.0"

# Physics & Movement
bevy_tweening = "0.16.0" 
avian2d = { version = "0.7.0", features = ["serialize", "bevy_diagnostic", "diagnostic_ui", "enhanced-determinism"] }
avian3d = { version = "0.7.0", features = ["serialize", "bevy_diagnostic", "diagnostic_ui", "enhanced-determinism"] }

# Network
lightyear = "0.29.0"

# Environment
bevy_hanabi = "0.19.0"

# Misc
bevy_rand = { version = "0.15", features = ["chacha20", "wyrand"] }
serde = { version = "1.0.229", features = ["derive"] } 