[package]
name = "all"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core Framework
bevy.workspace = true
bevy_dev_tools.workspace = true
bevy_framepace.workspace = true
moonshine-core.workspace = true

# GUI
egui_dock.workspace = true
egui-keyframe.workspace = true
egui_ltreeview.workspace = true
bevy-inspector-egui.workspace = true
bevy_gltf.workspace = true

# Input Handling / Action Mapping
leafwing-input-manager.workspace = true

# Asset Related
bevy_kira_audio.workspace = true
bevy_asset_loader.workspace = true
iyes_progress.workspace = true

# Tilemap & Level Design
bevy_ecs_tilemap.workspace = true
bevy_ecs_tiled.workspace = true
bevy_ecs_ldtk.workspace = true
bevy_northstar.workspace = true

# Physics & Movement
bevy_tweening.workspace = true
avian2d.workspace = true
avian3d.workspace = true

# Network
lightyear.workspace = true

# Environment
bevy_hanabi.workspace = true

# Misc
bevy_rand.workspace = true
serde.workspace = true
