[alias]
dev-build = "build --workspace --features bevy/dynamic_linking"
dev = "run --features bevy/dynamic_linking"
exam = "run --features bevy/dynamic_linking --example"

# someday maybe
pub = "publish --workspace --no-verify"